language: c

sudo: required

services:
  - docker

before_install: # update to 17.05 to get multistage builds
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - make e2e-vpnkit-tap-vsockd
  - cd go && make build-in-container
